name: docker-build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose --profile cpu build

  verify-valkey:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Valkey JSON module present
        run: |
          docker run -d --name valkey-check valkey/valkey-extensions:8.1-bookworm
          for i in {1..5}; do
            if docker exec valkey-check valkey-cli MODULE LIST | grep -q valkeyjson; then
              docker rm -f valkey-check
              exit 0
            fi
            sleep 1
          done
          echo "Valkey JSON module missing or server failed to start"
          docker logs valkey-check || true
          docker rm -f valkey-check
          exit 1
