name: docker-build
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: docker compose --profile cpu build

  verify-valkey:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Valkey JSON module present
        run: |
          docker run --rm valkey/valkey-extensions:8.1-bookworm \
            valkey-cli MODULE LIST | grep -q valkeyjson
