name: frontend
on:
  pull_request:
    paths:
      - 'ui-react/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: ui-react
      - run: npx playwright install --with-deps
        working-directory: ui-react
      - run: npm run build
        working-directory: ui-react
      - run: npm run e2e -- --reporter=line
        working-directory: ui-react
