name: build-tools
on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/tools.Dockerfile
          push: false
          cache-from: type=gha,scope=dev-img
          cache-to: type=gha,scope=dev-img,mode=max
